# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
  use_frameworks!

target 'SSPageViewController' do
  inhibit_all_warnings!
  pod 'SnapKit'
  pod 'MJRefresh'
end
