# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
  use_frameworks!

target 'SSPageViewController' do
  inhibit_all_warnings!
  pod 'SSPage-Swift', :path => '../../../SSPage'
  pod 'SnapKit'
  pod 'MJRefresh'
end
